version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Mexico_City
    open-pull-requests-limit: 5
    labels:
      - dependencias
      - python
    groups:
      dependencias-python:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Mexico_City
    open-pull-requests-limit: 5
    labels:
      - dependencias
      - github-actions
    groups:
      acciones-github:
        patterns:
          - "*"
